### ISSUE TITLE
Usage as a layer in another project

### ISSUE THREAD

**Issue by paambaati** [erezrokah/lighthouse-layer#4]
I'm trying to automatically pull in `lighthouse-layer` as a layer/dependency into an existing project. I want to make sure my own serverless function can use `lighthouse-layer` as a Layer; how do I do that?

Here's what I've tried -

1. Add `https://github.com/erezrokah/lighthouse-layer` as a git submodule to my serverless project and add it as a layer.

	```yaml
	layers:
	  lighthouse:
	    path: lighthouse-layer # assuming this is where this project is added as a git submodule
	```
    This fails with an error —
	```
	Serverless Error ---------------------------------------
	
	No file matches include / exclude patterns
	```

I'd like a way to do this seamlessly so there's no external dependency; currently, anyone running my serverless function has to have `lighthouse-layer` already deployed, which isn't ideal. I'd like to enforce installing the layer as a dependency for my function.

**Comment by paambaati** [comment]
Update:

I tried running a `sls package` inside the submodule directory, and then added the created `lighthouse.zip` as a layer, and it seems to work for now.

```yaml
layers:
  lighthouse:
    package:
      artifact: ./lighthouse-layer/.serverless/lighthouse.zip # Assuming it was built already with `cd lighthouse-layer && sls package`
```

However, once the Lambda is deployed, I'm getting an error (must not be connected to my original error) —

```json
{
	"errorType": "Runtime.ImportModuleError",
	"errorMessage": "Error: Cannot find module 'lighthouse'\nRequire stack:\n- /var/task/handler.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js"
}
```

Would I have to add `lighthouse` as a dependency to my own project as well? Would that not then pull in puppeteer and hence its own Chrome binary?

**Comment by erezrokah** [comment]
You need to deploy the layer to your account and then you use:
```yaml
functions:
  someFunction:
    layers:
      - arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:layer:lighthouse:12
```
